---
# An ansible playbook to configure RHEL 7 with the recommended practices to tune and run Oracle workloads.
# See links for further information.
# For RHEL & Oracle DB versions please see solution: https://access.redhat.com/solutions/39188
# For setting the Oracle tuned profile see solution: https://access.redhat.com/solutions/2867881
# 
# How to run playbook:
#
# ansible-playbook -vvv prep_oracle_sys.yaml
 
- hosts: 127.0.0.1
  connection: local
  gather_facts: yes
  tasks:
  - name: "get the rpm package facts"
    package_facts:
      manager: "auto"
  - name: "Checking GRUB cmdline for numa"
    shell: "grep 'GRUB_CMDLINE_LINUX=.*numa.*' /etc/default/grub"
    register: grub_cfg_grep_numa
    changed_when: false
    failed_when: false
  - name: "Checking GRUB cmdline for transparent"
    shell: "grep 'GRUB_CMDLINE_LINUX=.*transparent.*' /etc/default/grub"
    register: grub_cfg_grep_transparent
    changed_when: false
    failed_when: false
  - name: "Install tuned-profiles-oracle package"
    block:
    - name: "Enable rhel-7-server-optional-rpms repository"
      rhsm_repository:
        name: rhel-7-server-optional-rpms
        state: enabled
    - name: "Install tuned-profiles-oracle rpm"
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - tuned-profiles-oracle
        - tuned
    when: '"tuned-profiles-oracle" not in ansible_facts.packages'
  - name: "Disable NUMA in /etc/default/grub"
    block:
    - set_fact:
        date: "{{ansible_date_time.iso8601}}"
    - name: "Make backup of /etc/default/grub"
      ansible.builtin.copy:
        src: "/etc/default/grub"
        dest: "/etc/default/grub.{{ date }}"
      when: (grub_cfg_grep_numa.rc == 1) or
            (grub_cfg_grep_transparent.rc == 1)
    - name: "Configuring GRUB cmdline for numa"
      replace:
        path: '/etc/default/grub'
        regexp: '^GRUB_CMDLINE_LINUX="((\w.?)*)"$'
        replace: 'GRUB_CMDLINE_LINUX="\1 numa=off"'
      register: grub
      when: grub_cfg_grep_numa.rc == 1
    - name: "Configuring GRUB cmdline for transparent huge pages"
      replace:
        path: '/etc/default/grub'
        regexp: '^GRUB_CMDLINE_LINUX="((\w.?)*)"$'
        replace: 'GRUB_CMDLINE_LINUX="\1 transparent_hugepage=never"'
      register: grub
      when: grub_cfg_grep_transparent.rc == 1
  - name: "Update the bootloader config from /etc/default/grub"
    command: |
        grub2-mkconfig -o /boot/grub2/grub.cfg
    when: grub.changed
  - name: "Configure the tuned service"
    block:
    - name: "Make sure tuned is enabled & running"
      service:
        name: tuned
        state: started
        enabled: yes
    - name: "Get active profile"
      command: tuned-adm active
      register: tuned
      changed_when: false
    - debug: var=tuned.stdout_lines
      changed_when: false
    - name: "Set the tuned-profiles-oracle profile"
      command: tuned-adm profile oracle
      when: '"Current active profile: virtual-guest" in tuned.stdout_lines'
    - name: "Get active profile"
      command: tuned-adm active
      register: tuned
      changed_when: false
    - debug:
        msg: "Oracle profile is now set"
      when: '"Current active profile: oracle" in tuned.stdout_lines'
